spring.application.name=eventlogger
spring.datasource.url=jdbc:postgresql://localhost:5433/event_db
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
